spring:
  application:
    name: delivery-service
  
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  
  datasource:
    url: "jdbc:h2:mem:deliverydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: PUBLIC
    user: sa
    password: password
    url: jdbc:h2:mem:deliverydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration

server:
  port: 8082
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.delivrey: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

app:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  cache:
    type: simple
    cache-names:
      - customers
      - deliveries
      - tours

# Configuration Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
    filter: true
    persistAuthorization: true
    tryItOutEnabled: true
    syntaxHighlight:
      activate: true
  show-actuator: true
