server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

spring:
  config:
    activate:
      on-profile: default
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  autoconfigure:
    exclude: org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: sk-dummy-key

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    com.delivrey: DEBUG
    org.springdoc: DEBUG
    org.springdoc.api.OpenApiResource: TRACE
    org.springdoc.webmvc.api.OpenApiResource: TRACE
  application:
    name: delivery-service

task:
  execution:
    thread-name-prefix: DeliveryTask-
    pool:
      core-size: 2
      max-size: 10
      queue-capacity: 500

---
# Development profile (H2)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:deliverydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false
  web:
    base-path: /api  # This ensures H2 console works with the context path
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
      javax.persistence.schema-generation.database.action: update
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.type: trace
      temp:
          use_jdbc_metadata_defaults: false

---
# QA profile (PostgreSQL)
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:delivery_qa}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Liquibase configuration
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
  default-schema: public
  enabled: true
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD:postgres}
  url: ${spring.datasource.url}
  driver: ${spring.datasource.driver-class-name}
  contexts: qa
