spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/delivery_qa}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    default-schema: public

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      base-url: https://api.openai.com/v1/
      chat:
        model: gpt-3.5-turbo
        temperature: 0.5

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

optimizer:
  type: ai
